package io.santhoshkani.learn.mariadb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContinentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContinentAllPropertiesEquals(Continent expected, Continent actual) {
        assertContinentAutoGeneratedPropertiesEquals(expected, actual);
        assertContinentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContinentAllUpdatablePropertiesEquals(Continent expected, Continent actual) {
        assertContinentUpdatableFieldsEquals(expected, actual);
        assertContinentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContinentAutoGeneratedPropertiesEquals(Continent expected, Continent actual) {
        assertThat(actual)
            .as("Verify Continent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContinentUpdatableFieldsEquals(Continent expected, Continent actual) {
        assertThat(actual)
            .as("Verify Continent relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContinentUpdatableRelationshipsEquals(Continent expected, Continent actual) {
        // empty method
    }
}
