package io.santhoshkani.learn.mariadb.domain;

import static io.santhoshkani.learn.mariadb.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CountryStatsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryStatsAllPropertiesEquals(CountryStats expected, CountryStats actual) {
        assertCountryStatsAutoGeneratedPropertiesEquals(expected, actual);
        assertCountryStatsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryStatsAllUpdatablePropertiesEquals(CountryStats expected, CountryStats actual) {
        assertCountryStatsUpdatableFieldsEquals(expected, actual);
        assertCountryStatsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryStatsAutoGeneratedPropertiesEquals(CountryStats expected, CountryStats actual) {
        assertThat(actual)
            .as("Verify CountryStats auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryStatsUpdatableFieldsEquals(CountryStats expected, CountryStats actual) {
        assertThat(actual)
            .as("Verify CountryStats relevant properties")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getPopulation()).as("check population").isEqualTo(expected.getPopulation()))
            .satisfies(a -> assertThat(a.getGdp()).as("check gdp").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getGdp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryStatsUpdatableRelationshipsEquals(CountryStats expected, CountryStats actual) {
        assertThat(actual)
            .as("Verify CountryStats relationships")
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()));
    }
}
