package io.santhoshkani.learn.mariadb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVipAllPropertiesEquals(Vip expected, Vip actual) {
        assertVipAutoGeneratedPropertiesEquals(expected, actual);
        assertVipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVipAllUpdatablePropertiesEquals(Vip expected, Vip actual) {
        assertVipUpdatableFieldsEquals(expected, actual);
        assertVipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVipAutoGeneratedPropertiesEquals(Vip expected, Vip actual) {
        assertThat(actual)
            .as("Verify Vip auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVipUpdatableFieldsEquals(Vip expected, Vip actual) {
        assertThat(actual)
            .as("Verify Vip relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVipUpdatableRelationshipsEquals(Vip expected, Vip actual) {
        assertThat(actual)
            .as("Verify Vip relationships")
            .satisfies(a -> assertThat(a.getGuests()).as("check guests").isEqualTo(expected.getGuests()))
            .satisfies(a -> assertThat(a.getEvents()).as("check events").isEqualTo(expected.getEvents()));
    }
}
